# Plugins
gems:             ['jekyll-paginate', 'jekyll-gist', 'jekyll-github-metadata']

# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            TemizSpace
tagline:          Black Theme for Jekyll
description:      "We are creating open source kit-software and devices."
url:              https://github.com/karloespiritu/blackdoc
baseurl:          https://temizspace.github.io/

author:
  name:           'Karlo Espiritu'
  url:            https://twitter.com/karloespiritu

paginate:         5

# Custom vars
version:          1.0.1

github:
  repo:           https://goo.gl/4LxyZm
